version: '2.6.1'
services:

  square-service:
    image: sivakumargampala/square-service:v1
    container_name: square-service       
    ports:
      - "8091:8091"
    restart: always    
    networks:
      - calculator-compose-network

  cube-service:
    image: sivakumargampala/cube-service:v1
    container_name: cube-service       
    ports:
      - "8092:8092"
    restart: always    
    networks:
      - calculator-compose-network

  factorial-service:
    image: sivakumargampala/factorial-service:v1
    container_name: factorial-service      
    ports:
      - "8093:8093"
    restart: always    
    networks:
      - calculator-compose-network

# Networks to be created to facilitate communication between containers
networks:
  calculator-compose-network: