version: '2.6.1'
services:
  web-client:
    #image: sivakumargampala/calculator-web-client:v1
    build: ./web-client
    container_name: web-client
    ports:
      - "80:80"
    restart: always
    depends_on:
      - square-service
      - cube-service
      - factorial-service      
    networks:
      - calculator-compose-network
    
  square-service:
    image: sivakumargampala/square-service:v1
    #build: ./square-service
    container_name: square-service       
    ports:
      - "8091:8091"
    restart: always  
    networks:
      - calculator-compose-network

  cube-service:
    image: sivakumargampala/cube-service:v1
    #build: ./cube-service
    container_name: cube-service       
    ports:
      - "8092:8092"
    restart: always    
    networks:
      - calculator-compose-network

  factorial-service:
    image: sivakumargampala/factorial-service:v1
    #build: ./factorial-service
    container_name: factorial-service      
    ports:
      - "8093:8093"
    restart: always    
    networks:
      - calculator-compose-network      
  curl-service:
    image: curlimages/curl
    command: sleep 3600
    networks:
      - calculator-compose-network
   
# Networks to be created to facilitate communication between containers
networks:
  calculator-compose-network: