version: '2.6.1'
services:
  web-client:
    image: sivakumargampala/calculator-web-client:v1
    container_name: web-client
    ports:
      - "80:80"
    restart: always
    depends_on:
      - square-service
      - cube-service
      - factorial-service      
    networks:
      - calculator-compose-network
    
  square-service:
    image: sivakumargampala/square-service:v1
    container_name: square-service       
    ports:
      - "8091:8091"
    restart: always  
    networks:
      calculator-compose-network:
         ipv4_address: 172.20.0.1

  cube-service:
    image: sivakumargampala/cube-service:v1
    container_name: cube-service       
    ports:
      - "8092:8092"
    restart: always    
    networks:
      calculator-compose-network:
        ipv4_address: 172.20.0.2

  factorial-service:
    image: sivakumargampala/factorial-service:v1
    container_name: factorial-service      
    ports:
      - "8093:8093"
    restart: always    
    networks:
      calculator-compose-network:
         ipv4_address: 172.20.0.3

# Networks to be created to facilitate communication between containers
networks:
  calculator-compose-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          #docker-compose v3+ do not use ip_range
          ip_range: 172.28.5.0/24